import {readFile,writeFile,cp,mkdir,rm} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const release=JSON.parse(await readFile(path.join(root,'release.json'),'utf8'));
const configured=/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(release.repository);
if(!configured && process.env.VERCEL) throw new Error('배포 전에 release.json의 repository를 설정하세요.');
if(configured && !/^[a-f0-9]{64}$/i.test(release.sha256)) throw new Error('다운로드 ZIP의 SHA-256 값이 필요합니다.');
const site=(release.siteUrl || (process.env.VERCEL_PROJECT_PRODUCTION_URL ? `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}` : '')).replace(/\/$/,'');
if(site && !/^https:\/\/[a-z0-9.-]+$/i.test(site)) throw new Error('siteUrl은 HTTPS 도메인이어야 합니다.');
const repo=`https://github.com/${release.repository}`;
const replacements={VERSION:release.version,SIZE:`${(release.bytes/1000000).toFixed(1)} MB`,DOWNLOAD_URL:configured?`${repo}/releases/latest/download/${encodeURIComponent(release.asset)}`:'#download',RELEASE_URL:configured?`${repo}/releases/latest`:'#download',DOWNLOAD_STATE:configured?'':'aria-disabled="true" tabindex="-1"',DOWNLOAD_LABEL:configured?'Windows용 다운로드':'다운로드 연결 준비 중',SOCIAL_IMAGE:`${site}/assets/social-card.png`};
let html=await readFile(path.join(root,'public/index.html'),'utf8');
html=html.replace(/\{\{([A-Z_]+)\}\}/g,(_,key)=>{if(!(key in replacements))throw new Error(`Unknown template: ${key}`);return replacements[key]});
if(site)html=html.replace('</head>',`  <link rel="canonical" href="${site}/">\n  <meta property="og:url" content="${site}/">\n</head>`);
const dist=path.join(root,'dist');
await rm(dist,{recursive:true,force:true});
await mkdir(dist,{recursive:true});
await cp(path.join(root,'public'),dist,{recursive:true});
await writeFile(path.join(dist,'index.html'),html);
await writeFile(path.join(dist,'release.json'),JSON.stringify(release,null,2)+'\n');
await writeFile(path.join(dist,'robots.txt'),`User-agent: *\nAllow: /\n${site?`Sitemap: ${site}/sitemap.xml\n`:''}`);
if(site)await writeFile(path.join(dist,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>${site}/</loc></url></urlset>`);
console.log(`Built desktop-keyring v${release.version}; download ${configured?'connected':'awaiting GitHub repository'}`);
